version: 2
updates:
  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - "area: source"
      - "kind: maintenance"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - "area: automation"
      - "kind: maintenance"
